version: "3"

services:
  app:
    image: node:12
    container_name: web_container_test 
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - . :/app
    working_dir: /app
    command: npm start

  db:
    image: mysql:5.7
    container_name: db_container_test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306


